[package]
name = "heap-inspector"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
warp = "0.3.3"
tokio = { version = "1.23.0", features = ["full"] }
open = "3.2.0"
