name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: cd wasm/snapshot_parser && cargo test --verbose
    - name: Run test2
      run: cd wasm && cargo test --verbose
